services:
  db:
    image: postgres:16
    container_name: negosyante-db
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: negosyante
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
