name: Prisma Migrations and Build

on:
  push:
    branches: [ main ]

jobs:
  migrate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PRISMA_DATA_PROXY_URL: ${{ secrets.PRISMA_DATA_PROXY_URL }}
            # If PRISMA_DATA_PROXY_URL is set, Prisma will use the Data Proxy.
        run: npx prisma generate

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Build Next app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: npm run build
